# Travis CI Configuration file
# @link https://travis-ci.org/

# Using Java for the project
before_script: cd nexus-city-data-consumer
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script:
  # Unit and integration tests are run
  - mvn clean install
